name: Continuous Deployment

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

run-name: Deploy ${{ github.event.ref }}

jobs:
  gen-release:
    runs-on: ubuntu-latest
    steps:
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

  container:
    runs-on: ubuntu-latest
    needs: gen-release
    steps:
      - id: no-v
        uses: actions/github-script@v7
        with:
          script: |
            const tag = '${{ github.ref }}';
            const noV = tag.replace(/^v/, '');
            core.setOutput('no-v', noV)

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/timecopsync/crud:${{ steps.no-v.outputs.no-v }},ghcr.io/timecopsync/crud:latest
